language: python
python:
    - 3.5
    - 3.4
    - 3.3
    - 2.7
node_js:
  - 4
sudo: false
before_install:
    - pip install -r requirements.txt
    - pip install pytest
    - pip install pytest-cov
    - pip install codecov
install:
    - pip install -e .
script:
    - py.test -l --cov-report html --cov=nbdime
after_success:
    - codecov
